### ISSUE TITLE
html-template generates anonymous-schemas

### ISSUE THREAD

**Issue by djdjoko** [asyncapi/html-template#239]
Hello,

I am trying to generate html documentation with the html-template (Windows 10.0) but it renders additional properties to the schemas in the html such as <anonymous-schema-1>, <anonymous-schema-2> and <anonymous-schema-3>

I have tried running the following command to generate the html template.
ag https://raw.githubusercontent.com/asyncapi/asyncapi/v2.1.0/examples/simple.yml @asyncapi/html-template -o output

When I run it via the docker example, I get the same behaviour. 

![image](https://user-images.githubusercontent.com/902354/126501126-0a4aa41f-120f-449d-b33b-ddee3baae16f.png)

Could you please help me with this?

Thanks

**Comment by magicmatatjahu** [comment]
@djdjoko Hi! It's not a bug, but intentional decision. We render each schemas (not only in the `components/schemas` section) but also in the other, like plain schemas in the `message/payload` etc (by this you see `anonymous...`). As I look at it, it looks pretty weird and will only cause more and more problems from UX side, so I'm going to create a PR to fix this right now. Thanks for the issue!

**Comment by djdjoko** [comment]
Hi, thanks for the quick reply. I am trying to write a complex schema with multiple files and this issue seems to compound when I reference to other files:


```
# simple.yml
asyncapi: '2.1.0'
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup:
    subscribe:
      message:
        $ref: './simple_messages.yml'
```

```
# simple_messages.yml
summary: Receive quote updates on a given symbol.
payload:
  type: object
  properties:
    displayName:
      type: string
      description: Name of the user
    email:
      type: string
      format: email
      description: Email of the use   

```

The output it generates looks like this:

![image](https://user-images.githubusercontent.com/902354/126521067-29c9fb1b-f673-4bde-b54b-9bf97c73f845.png)

**Comment by magicmatatjahu** [comment]
@djdjoko Yes exactly, it infers all schemas, also subschemas. I merged fix in https://github.com/asyncapi/asyncapi-react/pull/399, so please wait few minutes to publish new version of html-template :)

**Comment by magicmatatjahu** [comment]
@djdjoko You can use the newest version of component `@asyncapi/html-template@0.23.4`. Let me know if everything is good :) Currently will be rendered only schemas from `components/schemas` section.

**Comment by djdjoko** [comment]
Thank you for the quick fix! It works if I render it from one file. If I render it from multiple files I am still getting following:

![image](https://user-images.githubusercontent.com/902354/126550470-36ef8257-cbea-438c-91fb-68196ee1aeb1.png)

Thanks again for looking into this!

**Comment by magicmatatjahu** [comment]
@djdjoko It's intentional 😄  https://github.com/asyncapi/parser-js, which produces the parsed schema in generator, treats some schemas (like plain schemas - without `$ref` - in the `message/payload` etc.) as anonymous, so by this you see the internal uid (anonymous) for the schema. If you think that it's a bug, please create the issue [here](https://github.com/asyncapi/asyncapi-react/issues/new?assignees=&labels=&template=bug-report.md).

**Comment by djdjoko** [comment]
Makes sense! Thanks again. I can set the Names with the `name` property in the multifile scenario :)

**Comment by magicmatatjahu** [comment]
@djdjoko Yes, I forgot about it that we try to use the `name` field and `anonymous...` is the fallback 😅

**Comment by derberg** [comment]
@magicmatatjahu we should not display any of `x-parser` related extensions in generated documentation, there are purely internal extensions not for user's eyes. Afaik we were hiding it everywhere in the past

**Comment by magicmatatjahu** [comment]
@derberg I know, and we don't render any internal extensions from parser, you can see filtering for that [here](https://github.com/asyncapi/asyncapi-react/blob/next/library/src/helpers/schema.ts#L259). Above problem was related to rendering of the messages and schemas. In previous solution we used `allMessages()` and `allSchemas()`  and if you used plain schema/message then you ended with `<anonymous-...>` name. Currently we render only messages/schemas from the components section.
